# Configuration file for unit test runner.
language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm
env:
  - PHPUNIT_ARGS=--group=sass
matrix:
  allow_failures:
    - php: hhvm
before_script:
  - cd tests
script: phpunit $PHPUNIT_ARGS
notifications:
  email: false
